### ISSUE TITLE
Cannot swipe the screen

### ISSUE THREAD

**Issue by osandadeshan** [robotframework/robotframework.github.com#103]
Need to swipe the screen from source coordinates to destination coordinates.
Is there is a keyword to do that?

**Comment by aikarjal** [comment]
Hi, I would assume that swiping in this context means using a mobile application. In this case, see e.g. http://serhatbolsu.github.io/robotframework-appiumlibrary/AppiumLibrary.html#Swipe

**Comment by osandadeshan** [comment]
@aikarjal 
I am asking from a web application

**Comment by pekkaklarck** [comment]
It would help others helping you if you'd provide enough information about your context. Also, this is a wrong place for this kind of questions.

**Comment by osandadeshan** [comment]
Yes I have posted in wrong place.
https://github.com/robotframework/SeleniumLibrary/issues/1246
