### ISSUE TITLE
New Editor Tools to be add

### ISSUE THREAD

**Issue by browncrane** [robotframework/robotframework.github.com#104]
There is a  `Robot Framework Intellisense`  `VScode` extension which has 40k download already.
The project is held in https://github.com/tomi/vscode-rf-language-server.
Extension page is on https://marketplace.visualstudio.com/items?itemName=TomiTurtiainen.rf-intellisense

**Comment by Tattoo** [comment]
Thanks for contributing! The extension looks awesome!
