### ISSUE TITLE
New robotframework user to add 

### ISSUE THREAD

**Issue by sergialonsoalpha** [robotframework/robotframework.github.com#105]
## Name of the company: 
Alpha
## Description:
At [Alpha](http://www.alpha.company/), we are developing the future of mobile apps for Health, with the latest advances in neuroscience, AI and mobile computing. *Robotframework* is a key part of our Health Moonshot development process to help us automatize testing for our projects and guarantee the best quality.
## Link:
http://www.alpha.company/
## Logo: 
![logo](https://user-images.githubusercontent.com/45431066/50075456-506a7680-01df-11e9-93f2-ef18070b2f5d.jpg)

**Comment by Tattoo** [comment]
Hi @sergialonsoalpha ,

The logo you have provided does not work in the white background the Users section has. You can see from this issue how your logo would look like. Do you want me to use it nevertheless, or provide a logo that works on white background?

Another thing, your description is unfortunately too lengthy. [As per instructions](https://github.com/robotframework/robotframework.github.com), the description should be around 200 characters long, whereas yours is 450+. If you could shorten it up and maybe tell what you are using Robot Framework for? For example, what kind of applications you are testing it with.

**Comment by sergialonsoalpha** [comment]
Hi @Tattoo,

Many thanks for your feedback.

I've already shorten the description of the company to fit your 200 characters long, sorry for the inconveniences. 

Also, I've updated a new logo with white background which I think it will works now with the User sections.

**Comment by pekkaklarck** [comment]
@Tattoo Do you have time to look at this?
