### ISSUE TITLE
Remote library is classified as both STANDARD and OTHER

### ISSUE THREAD

**Issue by adrianyorke** [robotframework/robotframework.github.com#108]
Remote library is listed as both a STANDARD and OTHER library with slightly different descriptions:

STANDARD
`Special library acting as a proxy..`

OTHER
`Built-in special library acting as a proxy..`

Suggested solution:
Remove OTHER listing.

**Comment by Tattoo** [comment]
In our experience, people have looked it from both places. Since there is no use case where having it multiple times on the page would be harmful, I don't really see any point in removing one or the other.
