### ISSUE TITLE
Robotframework syntax highlighting for Notepad++

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework.github.com#11]
https://github.com/robotframework/robotframework/issues/2283#event-501410782

Hello, 

I have created a Robot framework syntax highlighting for Notepad++ which is located at https://github.com/vkosuri/lang-robot

Below screen shot summaries the how it looks and color represents

```
Blue - Keywords
Orange - Variables
Green - Comments
```

![syntax-highlighter](https://cloud.githubusercontent.com/assets/13664257/12018694/650545a2-ad8c-11e5-8bf2-52719ab60f0a.png)

Where i can put lang-robot file?

**Comment by Tattoo** [comment]
Hi,

This looks good! Notepad++ is one of the most asked editors, at least from me. 

I linked to the Github repository.
