### ISSUE TITLE
"Let us know if your company or organization could be added here!"

### ISSUE THREAD

**Issue by Tuxedo21** [robotframework/robotframework.github.com#115]
Just wanted to let you know that Capgemini also uses Robotframework.

**Comment by Tattoo** [comment]
Hi @Tuxedo21! Would you like Capgemini to be listed in the Users section? In that case, if I could ask you to [provide the following information](https://github.com/robotframework/robotframework.github.com#adding-or-updating-resources) so we can add you in a way you control :)

**Comment by Tattoo** [comment]
Closing since not enought information
