### ISSUE TITLE
RIDE Editor doesnt load scripts at all

### ISSUE THREAD

**Issue by raman2k** [robotframework/robotframework.github.com#119]
Hi there,

I'm using RobotFramework to automate the tests that mainly need MQTT Library for testing pub-sub features on broker /clients.

I need the MQTT library(https://github.com/randomsync/robotframework-mqttlibrary), which only supports Python2- only commands (https://github.com/randomsync/robotframework-mqttlibrary/issues/5). The developer of this library, I guess doesn't know how to fix the issue, and is seeking help(as per the label "help wanted").

However, my project team uses Python 3.x( latest) for all their development and testing. I continuously juggle between the two versions when I test manually and when I write automation scripts.

Initially, I wasn't aware that MQTT Library was only compatible with Python 2.x and all my scripts were up and running until I upgraded RIDE to the latest version. Upon upgrading, I found that all my tests had stopped working. Ever since I've been trying to make things work. Then I had to downgrade RIDE to the previous version.  So now I have Robot Framework 3.1.1 and Ride v 1.5.2.1 installed on my work laptop. (Python 2.7.15)

When I try to run my scripts, the scripts run successfully. However, when I try to edit the scripts in RIDE editor, none of my scripts loads in the editor(Edit tab) well. When I click on "Text Edit", scripts only appear there.
![image](https://user-images.githubusercontent.com/20692270/52920691-60840b00-3374-11e9-8f79-e206274dc5b9.png)

I'm not a python developer, can not code "at all" in it, but my companies' developers who had a look at the RIDE log advises me that it seems that the issue seems to be with the framework.

Also, none of the functions appears in blue colour the way it usually appears in RIDE.
![image](https://user-images.githubusercontent.com/20692270/52920705-7d204300-3374-11e9-96cd-43a6c3071a34.png)

I've attached the RIDE Log. Please help. I'm stuck here, as it is affecting my productivity big time.

Kind regards,
Ramandeep Kaur

[Logs.txt](https://github.com/robotframework/robotframework.github.com/files/2873512/Logs.txt)

**Comment by raman2k** [comment]
https://github.com/robotframework/robotframework.github.com/issues/119 helped me

**Comment by goigly** [comment]
you could drop file which is ""C:\Users\Owner\AppData\Roaming\RobotFramework\ride\librarykeywords.db""

**Comment by raman2k** [comment]
That's the only thing that helped. Thank you!
