### ISSUE TITLE
robotframework syntax highlighter for gedit

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework.github.com#12]
Hello,

I have created a Robot framework syntax highlighting for **GEdit** and **Notepad++** which is located at https://github.com/vkosuri/lang-robot

Below screen shot summaries the how it looks and color represents

![disp-robot](https://cloud.githubusercontent.com/assets/13664257/12109041/108b99e0-b3a4-11e5-8770-2e0c1d8235e0.png)

I thought this will also be useful.

Thanks
Malli

**Comment by pekkaklarck** [comment]
Cool! I use GEdit often in demos and having syntax highlighting there is great.

Do Notepad++ and GEdit highlighting have something in common or is there some other reason you have them in same project? I would personally prefer separate projects, but if you prefer it this way that's fine too. Regardless of that, I guess there should be separate entries at http://robotframework.org about GEdit and Notepad++.

**Comment by vkosuri** [comment]
> Do Notepad++ and GEdit highlighting have something in common or is there some other reason you have them in same project?

No, both are entirely different.

Initially I felt one repository name generic for all projects anyway I created two separate repositories for both npp and gedit

https://github.com/vkosuri/npp-robot
https://github.com/vkosuri/gedit-robot

> I guess there should be separate entries at http://robotframework.org about GEdit and Notepad++.

Yes, It would be more convenient

**Comment by pekkaklarck** [comment]
Great, having separate projects is more clear in the longer run. @Tattoo, can you update the link to Notepad++ plugin and add GEdit plugin?

**Comment by vkosuri** [comment]
Thank you very much @pekkaklarck

**Comment by Tattoo** [comment]
Notepad++ was added in issue #11
