### ISSUE TITLE
New editor tool to add

### ISSUE THREAD

**Issue by Naaaaaaaaaaaaaaaaaj** [robotframework/robotframework.github.com#120]
Robotframework Debugger

This tool lets you debug robot files in visual studio code with call stack, breakpoints, variables that you can change, step out, step in and it is a 1 click install with configuration options.
Name of the library, tool, or other resource.

https://marketplace.visualstudio.com/items?itemName=JacobPhilip.danfoss-robotframework-debug

It is also #1 trending debugger currently on VS code marketplace.

**Comment by Tattoo** [comment]
Thanks for contributing!
