### ISSUE TITLE
Add Juniper Networks to Robotframework user page

### ISSUE THREAD

**Issue by aj226** [robotframework/robotframework.github.com#123]
Text to use:

"Juniper Networks has built an extensive automation framework on top of Robot Framework for end-to-end qualification of Juniper products to maintain our commitment to quality for our customers and users. It is used extensively in multiple groups including engineering and support amongst others. We have also worked with third-party test tool vendors to provide Robot Framework friendly APIs to integrate with our framework."

![juniper-networks-black-rgb](https://user-images.githubusercontent.com/26906319/55763314-4339f780-5a1b-11e9-84e6-1c211fc0ee42.png)

**Comment by aj226** [comment]
Please can this be addressed. thanks!

**Comment by stedtsa** [comment]
Done

**Comment by aj226** [comment]
thank you very much!
