### ISSUE TITLE
CAN Library

### ISSUE THREAD

**Issue by NaejEL** [robotframework/robotframework.github.com#125]
Hi, I've made a robotframework library to perform test on CAN BUS equipments.

Name: **CURF** (CAN UDS for RobotFramework)
Short description: _Library for testing CAN bus, support ISO-TP and UDS_.
Link: https://github.com/Openwide-Ingenierie/robotframework-can-uds-library
Name of my company: **SMILE** 
Logo of my company: https://www.smile.eu/themes/custom/smileeu/assets/images/icons/logo.png

**Comment by Tattoo** [comment]
Thanks for contributing!
