### ISSUE TITLE
PJSUA GPLv2 

### ISSUE THREAD

**Issue by buscseik** [robotframework/robotframework.github.com#127]
Hi All, 

I would like to create a voice test automation library for Robot framework built on PJSUA.
PJSUA is published with GPLv2. I am wondering if I publish with GPLv2, can it be used legally together with Robot Framework?
>If the main program dynamically links plug-ins, but the communication between them is limited to invoking the ‘main’ function of the plug-in with some options and waiting for it to return, that is a borderline case.
[GPLPlugins](https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins)

**Comment by pekkaklarck** [comment]
I think it's fine. RF and libs you use with it are separate projects not bundled together. Somewhat same as running non-GPL code on Linux that's itself GPL.

**Comment by pekkaklarck** [comment]
Also, sounds like a great library!
