### ISSUE TITLE
Add Segron to RF users page

### ISSUE THREAD

**Issue by yahman72** [robotframework/robotframework.github.com#131]
> Name of the library, tool, or other resource.

N/A

> Short description. Should not be longer than 200 characters.

Segron is a Bratislava-based company offering beyond End2End testing solution for Telecommunications. Our tool is based on Robot Framework and is the first true End2End solution for testing multiple interfaces and technologies with a single tool.

> Link to the resource.

www.segron.com

> When adding a new user, also include company/organization logo.

![Segron_LOGO_Transparent_01](https://user-images.githubusercontent.com/8724383/60358285-f2acb780-99d5-11e9-8994-d3b553c9b475.png)

**Comment by Tattoo** [comment]
Added in d10e3eb9fef576bd3d274b8d9ef51799769e475f.

Thanks for contributing!
