### ISSUE TITLE
ResultWriter doesn't generate proper log.html file (no info about keywords)

### ISSUE THREAD

**Issue by jurgenwigg** [robotframework/robotframework.github.com#132]
**Name of the tool**
Robot 

**Description**
In log.html there are no information about used keywords, even with TRACE log level set. 

**Source**

`
from robot.api import ResultWriter
from robot.api import TestSuite
from robot.conf import RobotSettings

suite = TestSuite('Activate Skynet')
settings = RobotSettings()
RobotSettings.log_level = 'TRACE'
suite.configure()

print(settings.log_level)

suite = TestSuite('Activate Skynet')
suite.set_tags('smoke', persist=True)

suite.resource.imports.library('OperatingSystem')
test = suite.tests.create('setting log level')
test.keywords.create('Set Log Level', args=['TRACE'])

result = suite.run(settings)
write = ResultWriter(result)
print(settings.get_rebot_settings())
write.write_results(settings.get_rebot_settings())
write.write_results(report="Test.html",
                    xunit="xunit.xml",
                    log="log.html")
`

**Comment by Tattoo** [comment]
@jurgenwigg,

This is not issue tracker for Robot Framework tool, but it's homepage robotframework.org.

Please report your issue to [Robot Framework's issue tracker](https://github.com/robotframework/robotframework/issues)
