### ISSUE TITLE
select from list

### ISSUE THREAD

**Issue by tkpat1526** [robotframework/robotframework.github.com#133]
hi i have lots off the dropdown menu in my project but there is no "SELECT" tab available so whenever I try to get lists its shows error.

**Comment by Tattoo** [comment]
Hi @tkpat1526,

This is issue tracker for the homepage robotframework.org, not a help forum. Please refer to [support section](http://robotframework.org/#support) to find approriate place -- for example, the mailing list or the Slack community could be good bets.
