### ISSUE TITLE
Request to add Organisation to Users list

### ISSUE THREAD

**Issue by saibharath9999** [robotframework/robotframework.github.com#138]
Company Name: HeyMath
Company Website: https://plp.heymath.com/
Description: HeyMath! is a comprehensive E-learning program with world-class creative digital content.We use Robot Framework for end-to-end automation testing for our Products and ensuring the quality before delivering to the end users.
![Heymath_Logo](https://user-images.githubusercontent.com/31496344/64598328-298b4a80-d3d5-11e9-9271-bf597ff67477.png)

**Comment by samipe** [comment]
Added!
