### ISSUE TITLE
Add Wärtsilä Digital Technologies to a user list

### ISSUE THREAD

**Issue by kabriolett** [robotframework/robotframework.github.com#139]
Company Name: Wärtsilä Digital Technologies
Company Website: https://www.wartsila.com/
Description: Wärtsilä Digital Technologies uses Robot to automate various types of testing. API testing, component testing, functional and system tests are used to ensure the highest quality of a wide variety of software. 
The Robot Framework helps us automate testing of mobile applications, web applications and cross-platform desktop applications.
![Wartsila_Logo](https://user-images.githubusercontent.com/55275307/64971040-aaec4c80-d8af-11e9-95ce-f6fabf7c37a6.png)

**Comment by samipe** [comment]
Added!

**Comment by kabriolett** [comment]
Layout is broken ;)
