### ISSUE TITLE
Add new external library: SoapLibrary

### ISSUE THREAD

**Issue by samuelpcabral** [robotframework/robotframework.github.com#146]
Short description:
This library is designed for those who want to work with webservice automation as if they were using SoapUI, make a request through an XML file, and receive the response in another XML file.

Link:
https://github.com/Altran-PT-GDC/Robot-Framework-SOAP-Library

**Comment by samipe** [comment]
Thanks, added in b0fb448626e778eb9d5b43b118965f59925f7a97
