### ISSUE TITLE
Add company to users list

### ISSUE THREAD

**Issue by ciaranflipdish** [robotframework/robotframework.github.com#148]
We are using RF extensively so would like to add our company to the users list.

Company Name: Flipdish
Company URL: https://www.flipdish.com/
Description: Flipdish are using Robot Framework for web. mobile and api, to enable us to test and release multiple white label products used for online ordering platforms across the globe.

Logo: 
![logo-big@2x_no_powered_by](https://user-images.githubusercontent.com/45640196/68467601-69708180-020e-11ea-985c-aac5aeb14eb7.png)

**Comment by samipe** [comment]
Thanks, added in 0921d193d7c43376efdfa70a94fc23a082a0c3b4
