### ISSUE TITLE
Add Altran company to users list

### ISSUE THREAD

**Issue by codecube** [robotframework/robotframework.github.com#149]
Hi, we would like be part of your user list in the RFW website.

Company Name: Altran
Company URL: https://www.altran.com/
Description: Altran is a world leader in engineering solutions and R&D, and is using extensively RobotFramework mainly in it's Global Engineering Centers. Altran is also an active contributor for the RobotFramework community and is the main developer of several RobotFramework libraries.

Logo:
![logo-execomm](https://user-images.githubusercontent.com/568134/68607641-fe8ea700-04a8-11ea-8300-45b1a0c92d64.png)

Thanks!

**Comment by samipe** [comment]
Thanks, added in 98851c9a0fe5bbf01e7f10e5ac977565b99db621
