### ISSUE TITLE
Library Dialogs can't run in shell

### ISSUE THREAD

**Issue by leimgitub** [robotframework/robotframework.github.com#153]
hi,
    I use Lirbrary Dialogs keywod, it can run in windows.
    But when I run it in shell, it is fail. It said "TclError: no display name and no $DISPLAY environment variable". 
    My question is: Does Dialogs only could run in windows?
   thanks.

**Comment by pekkaklarck** [comment]
This is a wrong place to ask questions. Find links to better places via robotframework.org.

**Comment by leimgitub** [comment]
sorry. I will change a place.

**Comment by pekkaklarck** [comment]
Please look at the docs first.
