### ISSUE TITLE
https://www.robotframework.org fails with cert error

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework.github.com#156]
https://robotframework.org works. Need to check why this happens.

**Comment by Snooz82** [comment]
@pekkaklarck @samipe 

This is because we only have `robotframework.org` in our Lets-Encrypt cerificate. 
We just have to add the subdomain `www.robotframework.org` to our update script.

**Comment by samipe** [comment]
Also I found this article about it: https://medium.com/@monarchwadia/github-pages-setting-up-www-subdomain-with-ssl-https-aca9eca371d6
Tried appending www to CNAME last week, but by itself it didn't work.

**Comment by Snooz82** [comment]
@samipe 

I think the best would be to add a redirection to the www domain to robotframework.org

A redirect would not cause any issues.

**Comment by samipe** [comment]
Fixed
