### ISSUE TITLE
Please add the Test Assistant to https://robotframework.org/#tools

### ISSUE THREAD

**Issue by jg8481** [robotframework/robotframework.github.com#158]
If possible, please add this to the tools section. Thank you.

**Name:** Test Assistant
**Description:** This conversational test assistant allows you to control test processes and RPA tasks with your voice, or with a text message sent directly to the assistant through a UI in your browser.
**Link:** https://github.com/jg8481/leon/tree/develop/packages/robotframework-test-assistant

FYI, it was covered here in the following in RoboCon 2020.

https://robocon.io/#strategies-for-creating-your-own-conversational-test-assistant-with-robot-framework-and-other-tools

**Comment by samipe** [comment]
Thanks, added in ad916015f492f4cdb4dcf960d7aa4dac933afab9
