### ISSUE TITLE
Please add "Zymr Inc " to the company list

### ISSUE THREAD

**Issue by bbpatel2001** [robotframework/robotframework.github.com#161]
Hi, 
we would like be part of your user list in the RFW website.

Company Name: Zymr Inc
URL: https://www.zymr.com/
Description: Zymr has deep expertise in the Robot Framework and using it extensively for automating the test cases for the clients in various industries. It has been used within Docker and other containers.

![ZymrLogo](https://user-images.githubusercontent.com/33742811/73842872-761f6880-4843-11ea-8270-2b755d755fad.png)

**Comment by gaurav294** [comment]
@pekkaklarck Can you please take a look ?

**Comment by Snooz82** [comment]
One think first:
could you please reduce the Description! Typical length is around 250 characters.
Your text is at the moment longer than 450 chars.

**Comment by gaurav294** [comment]
@bbpatel2001 please do needful !

**Comment by bbpatel2001** [comment]
updated. @gaurav294,please check.

**Comment by gaurav294** [comment]
@Snooz82 we have updated it..

**Comment by gaurav294** [comment]
@Snooz82 : For time being we have created PR `https://github.com/robotframework/robotframework.github.com/pull/163` once have time please review and merge it..

**Comment by bbpatel2001** [comment]
Closing this issue as we have created separate PR.
