### ISSUE TITLE
Examples and description doesn't match

### ISSUE THREAD

**Issue by ratzhub** [robotframework/robotframework.github.com#162]
There are 6 Examples provided and the corresponding description is supposed to be displayed above. 

But there is a mismatch between examples and description.

In the snapshot attached, the description is for Example 1 whereas Example 2 is selected currently.
Same issue is observed for all examples. Tested in Chrome/Firefox

![robo framework issue](https://user-images.githubusercontent.com/60685371/73870476-286e2480-4872-11ea-86d6-8952c23feeb4.jpg)

**Comment by pekkaklarck** [comment]
Yeah, examples have had issues since this page was redesigned about two years ago. We should form a task force to fix them and go through this page otherwise as well.

**Comment by janipalsamaki** [comment]
The fix itself would be simple:

In `Examples.vue`:

- Add `@input="changeTabText(tabIndex)"` to `b-tabs` element
- Remove all the click handlers from `b-tab` elements
