### ISSUE TITLE
Update link to robotframework-autoitlibrary  in the robotframework website

### ISSUE THREAD

**Issue by praveendvd** [robotframework/robotframework.github.com#165]
The robot framework website mentions robotframework-autoitlibrary in its external library listing and it points to http://code.google.com/p/robotframework-autoitlibrary/. I found a git repo https://github.com/nokia/robotframework-autoitlibrary and I believe that when I do pip install this is the library that's get installed.

Is this the new supported library , then could the website be updated by pointing to this repo instead.

**Comment by samipe** [comment]
Thanks, updated in c7f03b71141e9223ed332c79fbe2cdd6d2dfe050
