### ISSUE TITLE
Where the keywords link

### ISSUE THREAD

**Issue by vpinho13** [robotframework/robotframework.github.com#168]
Guys, sorry

I already try for hours to find some simple: Examples

open browser  == (Explanation about what this one does)

Select radio button = (explanation what this one does) 

This is must be very simple and clear, I cannot found. sorry

**Comment by Tattoo** [comment]
These keywords are part of 3rd party library [SeleniumLibrary](https://github.com/robotframework/SeleniumLibrary/) and you can find their documentation on the library's website.

To learn how Robot Framework key concepts and in general what you can do with it, please refer to the [Robot Framework user guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html)

You can also ask questions on the [various resources listed on the site](https://robotframework.org/#support). This issue tracker is for the website robotframework.org. If you have problems, please post your issue to the proper forum in the future.
