### ISSUE TITLE
Error in importing asammdf

### ISSUE THREAD

**Issue by shyamdb** [robotframework/robotframework.github.com#170]
Hello,

i have written a custom Library in python, which imports a package named "asammdf". But, when i import my custom Library in Robot code, it shows error in importing "asammdf" in python. It says: "Error in File *.robot. Importing test Library *.py failed. Import Error: DLL load failed: the specified module could not be found."

"asammdf" package is available in one of the PYTHONPATH it mentions during executions.

Can someone please help me doing this and let me know, what have i done wrong?

My python File (example.py):
import asammdf
...
...
...

My robot file (test.robot):
*** Settings ***
Library     example.py

*** Test Cases ***
TC1
     DO THIS
     DO THAT

Thanks in advance.

**Comment by Tattoo** [comment]
This issue tracker is for the website robotframework.org. If you have problems, please post your issue to the proper forum in the future.

It sounds like your code is not working properly. To learn how Robot Framework key concepts – like how to write libraries with Python – and in general what you can do with it, please refer to the [Robot Framework user guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html)

You can also ask questions on the [various resources listed on the site](https://robotframework.org/#support).
