### ISSUE TITLE
Add WADLibrary

### ISSUE THREAD

**Issue by damies13** [robotframework/robotframework.github.com#171]
I am not the maintainer of this library, however I managed to find it with a little searching.

While this library is not well documented it is useful for automating windows metro applications (windows 8+) so I think it should be added to the "Libraries > External" page to help others find it if they need to deal with windows metro applications.

https://github.com/Adwisit/WADLibrary

**Comment by samipe** [comment]
Thanks, added in caa4802cb07fcfaa26ce0ba04b810de2a7e2193e!
