### ISSUE TITLE
Please add Test Automation U free course to front page

### ISSUE THREAD

**Issue by dpm3354** [robotframework/robotframework.github.com#175]
Pekka said to add my new free online course (https://testautomationu.applitools.com/robot-framework-tutorial/) for RF here.

Can you please add it to the section of the front page for "Documentation"? The correct tab would be "Online Courses". Here is the correct text:

Introduction to Robot Framework (FREE) (link: https://testautomationu.applitools.com/robot-framework-tutorial/)

Want to learn Robot Framework? Learn the fundamentals in 1 hour with Test Automation University’s FREE course!

**Comment by dpm3354** [comment]
Would be best to make it the left-most option in that section, as it is the simplest, free course for absolute beginners. 

This course should help with adoption by beginners!

**Comment by samipe** [comment]
Thanks, added in e18c6c4facade7c1e54844b776a85838c8a210d3.
In the name of fairness, I placed it in alphabetical order as with all other links. Beginner friendliness and being free can be seen from it's description, simplest is subjective. ;)
