### ISSUE TITLE
Adding Testmo as Robot Framework user

### ISSUE THREAD

**Issue by dennisgrck** [robotframework/robotframework.github.com#193]
Hello,

I would like to suggest adding us (Testmo) as a Robot Framework user to the site. Here are the details:

Name: Testmo
Description: Testmo is a test management tool for modern software teams. The Testmo team uses Robot Framework for acceptance testing and to support its customers' QA.
Link: https://www.testmo.com/
Logo: ![image](https://user-images.githubusercontent.com/26714566/97081926-00903e00-1606-11eb-8166-705bdccff09c.png)

Thanks!

Dennis

**Comment by samipe** [comment]
Added to users, thanks!
