### ISSUE TITLE
Integration of Microsoft Azure and ROBOT

### ISSUE THREAD

**Issue by MonicaJacob** [robotframework/robotframework.github.com#195]
To use ROBOT for CI, are there plugins available for Microsoft Azure?

**Comment by Tattoo** [comment]
Hi, 

this issue tracker is for issues relating to website robotframework.org, not for general Q&A.

It would be best to direct your questions to several options listed in [robotframework.org Community section](https://robotframework.org/#community), for example the [Robot Framework Forum](https://forum.robotframework.org/) where you can reach other members of the community better.
