### ISSUE TITLE
Add rfswarm to help people become aware that they can use robotframework for performance testing.

### ISSUE THREAD

**Issue by damies13** [robotframework/robotframework.github.com#197]
Hi,

I am the maintainer of [rfswarm](https://github.com/damies13/rfswarm#rfswarm-robot-framework-swarm) and I would like to request that you add rfswarm to the robotframework page to help people become aware that they can use robotframework for performance testing.

I would suggest that the other tab of the [tools section](https://robotframework.org/#tools) is probably the best place for the link, but I'll leave that up to your discretion

https://github.com/damies13/rfswarm#rfswarm-robot-framework-swarm

Thanks,

Dave.

**Comment by samipe** [comment]
Added to tools, thanks!
