### ISSUE TITLE
Add TestDataTable to Tools 

### ISSUE THREAD

**Issue by damies13** [robotframework/robotframework.github.com#198]
Hi,

I am the maintainer of [TestDataTable](https://github.com/damies13/TestDataTable#testdatatable) and I would like to request that you add TestDataTable to the robotframework page.

I would suggest that the other tab of the [tools section](https://robotframework.org/#tools) is probably the best place for the link, but I'll leave that up to your discretion.

While TestDataTable does not require you to use robotframework it is a tool that could be very useful to people who use robotframework as it is a complimentary test tool and provides a way to transfer transient data between test cases.

https://github.com/damies13/TestDataTable#testdatatable

Thanks,

Dave.

**Comment by samipe** [comment]
Added to tools, thanks!
