### ISSUE TITLE
Add robotframework-flaui to LIBRARIES> EXTERNAL

### ISSUE THREAD

**Issue by damies13** [robotframework/robotframework.github.com#201]
Hi,

I found this [thread](https://forum.robotframework.org/t/automating-desktop-application-by-using-robot-framework/421/11) on the robotframework forum

I am not the maintainer of either of these libraries, so you may want to confirm with Roman, who appears to be the author and maintainer of FlaUI (and previous maintainer of White).

It appears the white Library in LIBRARIES> EXTERNAL is no longer being maintained, so you may want to replace it with FlaUI library or leave it there and add [FlaUI library](https://github.com/GDATASoftwareAG/robotframework-flaui) to the list

https://github.com/GDATASoftwareAG/robotframework-flaui

I'll leave this to your discretion as to the best course of action.

Dave.

**Comment by Nepitwin** [comment]
@damies13 Thanks for you creation for the request.

The open source implementation for the Robotframework-FlaUI is currently under maintenance and implementation by me.
This is based on the FlaUI library from Roman.

I would like to enter the information for a possible information update.

Name of the Library: Robotframework-Flaui

Description : Robotframework-FlaUI is a keyword based user interface automation testing library for Windows applications like Win32, WinForms, WPF or Store Apps. It's based on the FlaUI user interface automation library.

Link: https://github.com/GDATASoftwareAG/robotframework-flaui

**Comment by damies13** [comment]
Hi @Nepitwin Nice to know who the library maintainer is 👍🏼 I simply added this request as I believe your library will be useful to people and having it listed on the website makes it easier for people new to RF to find it. While I haven't used your library yet, it looks good, so thanks for creating and maintaining it.

**Comment by samipe** [comment]
Sorry for the "slight" delay. FlaUI has been added now!
