### ISSUE TITLE
Add robotframework-djangolibrary

### ISSUE THREAD

**Issue by tisto** [robotframework/robotframework.github.com#21]
Name of the library: 

robotframework-djangolibrary - A robot framework library for Django.

Short description (approximately 10 words):

DjangoLibrary is a web testing library to test Django with Robot Framework. It uses Selenium2Library to run tests against a real browser instance.

Link to the home page of the library (preferably just not the keyword documentation page):

https://pypi.python.org/pypi/robotframework-djangolibrary

**Comment by pekkaklarck** [comment]
Thanks, we try to get it added ASAP. If @Tattoo is on holiday, I can take care of it myself. If you @tisto want to make this very easy and fast for us, please submit a pull request adding the lib.

**Comment by tisto** [comment]
@pekkaklarck sure! Will look into it.

**Comment by tisto** [comment]
@pekkaklarck done: https://github.com/robotframework/robotframework.github.com/pull/22

**Comment by pekkaklarck** [comment]
Awesome, thanks! PR is merged and changes are live and look good.

I also updated this project README to explicitly mention the option to submit a PR instead of an issue.

**Comment by tisto** [comment]
@pekkaklarck awesome! thanks!
