### ISSUE TITLE
Add DependencyLibrary to external libraries list?

### ISSUE THREAD

**Issue by mentalisttraceur** [robotframework/robotframework.github.com#217]
I propose adding [DependencyLibrary](https://pypi.org/project/robotframework-dependencylibrary/) to the Libraries section.

When tests can't be independent, DependencyLibrary

1. makes dependencies explicit, and
2. makes dependent tests behave correctly (automatically fail or skip, with a clear message).

**Comment by samipe** [comment]
Sorry for the "slight" delay. DependencyLibrary has been added now! bf8b16201a5264ad52926ed429d5109d3a43e5f8
