### ISSUE TITLE
Add easy access to "Robot Framework User Guide" on frontpage

### ISSUE THREAD

**Issue by SkyFoxCoder** [robotframework/robotframework.github.com#229]
Hi,

Great improvement on the new website!
One thing that seems to have slipped is a "Robot Framework User Guide" link on the front page except by going in the footer (Instructions -> User guide)

[https://robotframework.org/robotframework/](https://robotframework.org/robotframework/)

Perhaps a link in "Getting Started" or "Resources" would be appropriate?
I'm having new users in mind that have no idea this documentation exists.

Thanks in advance!

**Comment by samipe** [comment]
Hi!

Thank you very much for your feedback. The user guide is linked under getting started -> tutorials also, though I agree it's not that obvious. I'll think for a better representation.

**Comment by samipe** [comment]
User guide has been added to a (hopefully) more visible place now, see if you can find it! :)

**Comment by Tattoo** [comment]
For me the new place in the top bar works wonderfully 💖 Great job @samipe !

**Comment by SkyFoxCoder** [comment]
> User guide has been added to a (hopefully) more visible place now, see if you can find it! :)

Thank you!
Exactly the clarity that was needed.
