### ISSUE TITLE
"Open space" link don't working

### ISSUE THREAD

**Issue by ludovicobesana** [robotframework/robotframework.github.com#230]
**Step by step:**

1- I reach robotframework website
2- I scroll to "Community" section
3- I click on "Open space" link

**Expected result:**
I expect to be rendered on google calendar and to see the procedure for adding the event

**Actual result:**
I am rendered on google calendar but no procedure is started to add the event

https://robotframework.org/#:~:text=Click%20for%20invite!-,Open%20space,-Meet%20the%20Robot

![Schermata 2021-11-03 alle 11 08 46](https://user-images.githubusercontent.com/35035423/140042368-51783395-e550-44a0-ab85-c3c820c5df44.png)

**Comment by mkorpela** [comment]
Same.

**Comment by mkorpela** [comment]
Link removed.
