### ISSUE TITLE
Add robotframework-doctestlibrary to list of libraries

### ISSUE THREAD

**Issue by manykarim** [robotframework/robotframework.github.com#234]
Please add the robotframework-doctest library to the list of libraries.
It is a library for Visual Document Testing.
https://github.com/manykarim/robotframework-doctestlibrary/

Pull request has already been created, I hope I entered the details properly
https://github.com/robotframework/robotframework.github.com/pull/233

**Comment by manykarim** [comment]
Hi @samipe , could you please have a look when you have time?
Please let me know in case I missed something to add or to do.
Thanks a lot!

**Comment by samipe** [comment]
Merged!
