### ISSUE TITLE
Redundant Information and Layout Issues

### ISSUE THREAD

**Issue by cogmind** [robotframework/robotframework.github.com#25]
---
I n f o r m a t i o n
There is too much info on the front page and the same links appear in two different places. Unnecessary abbreviations are introduced but never reused.

Compare with https://www.python.org/

How about

---

Robot Framework is a test automation framework for acceptance testing and test-driven development for Python and Java.

**Features**
- Tabulated test syntax
- Keyword-driven testing
- Meta-keywords

**Install**
pip install robotframework

**Contribute**
https://github.com/robotframework/robotframework

**License**
Apache 2.0

Robot Framework was initially developed by Nokia Networks. Today it is sponsored by Robot Framework Foundation.

-----
L a y o u t
In addition, the serif font is not easy on the eyes. If you insist on a serif typeface, you need at least half-spacing between rows, column text should be aligned to both sides, not just left. In general, shifting between centered and text and left-aligned text should be avoided.

**Comment by pekkaklarck** [comment]
Thanks for the feedback. 

Do you mean that some information should be removed altogether or that the information at the top of the page should be less verbose? Personally I find the information there valuable and would be careful when removing something, but I agree the first view people see shouldn't contain too much stuff.

Links appearing in multiple places isn't generally a problem, because we don't expect everyone to read the whole page. What concrete examples of unnecessary links do you have? Also, what abbreviations are unnecessary?

I don't know enough about web design to be able to comment much about the layout. Do you have concrete proposals, perhaps in format of a pull request, that we could evaluate?

**Comment by Tattoo** [comment]
Do note that robotframework.org is the "frontpage" of the whole RF ecosystem, not just the tool itself. The whole point of the site is to collect everything interesting on the same page, being a portal and jump-off point for everyone. If you are planning on contributing for a better site, please take this into consideration.

**Comment by cogmind** [comment]
It is not so much a matter of content, but of human computer interaction. Information on pages should ideally be self-contained. This is analogous to encapsulation. What _must_ the visitor know in order to stay on the web page?

Furthermore, one might ask Who is the audience? In my case, I stumbled upon the Robot Framework as I was learning about acceptance and unit testing. Should the front page introduce the Robot Framework to newcomers, should it cater to experienced users, or both? I think the answer is obvious.

There should be one way and one way only to navigate to a web page. This is a principle that reduces the navigation interface to its bare essentials. Imagine that another principle applied: "All roads lead to Rome". At what point would the navigation interface become saturated?

To answer the question about abbreviations. In technical writing, formally, if An Abbreviation Is Introduced (e.g. AAII) it should be reused. If it is not reused, this could indicate jargon, and that is appropriate in a context of experienced users, but perhaps less so if AAII for the sake of communicating the jargon. It is somewhat uninviting. Like TDD.

Concerning potential contributions, I am still learning about testing and software development in general. I think that, given a choice, concise information sources are preferable. If I find Robot Framework useful I might decide to contribute to the web page, but I am still an early process of learning. In my opinion, I would only take the above feedback into account if you are given similar input from other users.

My 2 cents

**Comment by Tattoo** [comment]
If you come to the conclusion to contribute to the site, please open a new issue for it then.

**Comment by cogmind** [comment]
@Tattoo Thanks for your time.
