### ISSUE TITLE
getting error While executing the test as mentioned in the comments

### ISSUE THREAD

**Issue by Nani22git** [robotframework/robotframework.github.com#266]
ImportError: cannot import name 'Mapping' from 'collections' (D:\Users\HYeginen\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)
2022-07-09 17:50:32,817 - Robot.Driver - _delete_file - INFO - Deleting file: D:\RVR 3\test\Rest_API\Robot_Arguments__

Anyone can help on this

**Comment by mkorpela** [comment]
Hi @Nani22git 
This is the issue tracker for robotframework.org web site. For Robot Framework related issues please go to https://github.com/robotframework/robotframework
