### ISSUE TITLE
Add Smart Synergies to User Page

### ISSUE THREAD

**Issue by smsybv-github** [robotframework/robotframework.github.com#294]
We would like you to consider our company to be part of your user page.

Smart Synergies promotes Robotframework as the "Swiss Army Knife" of Software testing tools in the wide and open seas of commercial and open-source software testing tools and applies it since 2014 with great success to its customer's test automation projects. Smart Synergies delivers end-2-end test automation services from building pilots demoing Robotframeworks powers to making it part of the continuous integration pipeline, from creating test automation strategies to designing and implementing test scenarios and cases.

Our web presence [Smart Synergies](www.smart-synergies.eu) 

<img width="375" alt="smart-synergies-digital-business-solutions" src="https://user-images.githubusercontent.com/59796443/219958282-3322c3eb-c9ba-4132-aa3b-313c76a3fab2.png">

**Comment by samipe** [comment]
Added in 0515603d702b438eace5031f96c278f34c2143be. Thanks!
