### ISSUE TITLE
Reorganize Support section

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework.github.com#33]
- [x] Remove references to unused mailing lists
- [x] List `robotframework-users` only in the "main bullets"
- [x] Remove `robotframework.org` from these lists altogether
- [x] Move blogs under Documentation (#31)
- [x] New "Other forums" sub section that lists remaining email lists, LinkedIn, and other free forums. This section should be full width with 2 or 3 internal columns like with libs and tools.
- [x] Add Stackoverflow and Helsinki Meetup (#30 and #29) under the above "Other forums" section
- [x] Add "Paid support" section with the current paid support links and with links referring to foundation companies.
- [x] Introduction text with "Let us know..." link instructing how to get new items added.
- [x] Possibly reorganize "main bullets" to avoid the current T shape 
- [x] Notify people on rf-users, Twitter, LinkedIn, etc. and ask them to submit issues/PRs if they want their forums, companies, etc. added.

**Comment by pekkaklarck** [comment]
Once this is done, we should notify people on rf-users, Twitter, LinkedIn, etc. and ask them to submit issues/PRs if they want their forums, companies, etc. added.

**Comment by pekkaklarck** [comment]
First version of the intro text to be added to this section:

> There are various forums where to ask questions and discuss about Robot Framework and the ecosystem around it in general. There are also several companies around the world that provide paid support, consultation, and training courses related to the framework. [Let us know](https://github.com/robotframework/robotframework.github.com) if there is a support forum or a company offering related services you would like to be added here.

**Comment by Tattoo** [comment]
Additionally:

- [ ] Move rf-devel and rf-announce to "Other forums"
- [ ] Change meetup.com to "RF Helsinki Meetups" with description "Robot Framework Meetup group at Helsinki, Finland"
