### ISSUE TITLE
New Users section

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework.github.com#34]
New section to list companies using Robot Framework. Content:

- Short section introduction with "Let us know..." link asking users to submit issues/PRs if they want their company/organization to be added.
- Each company/organization listed with a logo or name and short text explaining how and where (domain) used.

Need some examples before we can publish this. After that should ask people on rf-users and elsewhere to submit more.

**Comment by pekkaklarck** [comment]
First version of the intro text for this section:

> Robot Framework is used very widely around the world in different domains and contexts. [Let us know](https://github.com/robotframework/robotframework.github.com) if your company or organization could be added here!

**Comment by Tattoo** [comment]
Live since bf2be21a902ad8f85ff37ce272a6cd93d2120d24

To do:

- [ ] Add link to menu bar
