### ISSUE TITLE
External Libraries link to AutoItLibrary broken

### ISSUE THREAD

**Issue by mh182** [robotframework/robotframework.github.com#39]
Issue https://github.com/robotframework/robotframework/issues/2585 moved to the right project:

The link of AutiItLibrary in the http://robotframework.org/#libraries section points to https://code.google.com/archive/p/robotframework-autoitlibrary/ which returns a 401 error.

I alternatives version of the library on GitHub but I do not know which one is the migrated version from Google Code.

**Comment by Tattoo** [comment]
Old link works for me. Maybe Google Code was having issues? Can you confirm that it works for you?

**Comment by mh182** [comment]
The link works for me now. Probably Google Code had problems.

I will close the issue.
