### ISSUE TITLE
robotframework.org links to robotframework-commit, not in use since 2009

### ISSUE THREAD

**Issue by guykisel** [robotframework/robotframework.github.com#4]
The mailing lists section of robotframework.org links to https://groups.google.com/forum/#!forum/robotframework-commit but this mailing list appears to be unused since 2009.

**Comment by guykisel** [comment]
Looks like this was fixed in https://github.com/robotframework/robotframework.github.com/pull/6

**Comment by pekkaklarck** [comment]
Had totally forgotten about this. You are right that #6 is a duplicate and this is thus fixed too.
