### ISSUE TITLE
Ryerson University would like to be added to Users section

### ISSUE THREAD

**Issue by Mattje1** [robotframework/robotframework.github.com#44]
Ryerson University uses Robot Framework to conduct desktop and mobile browser testing for its suite of applications that serve both students and staff.

Logo
![ryerson-rgb](https://user-images.githubusercontent.com/7376993/30930341-7358c02a-a38f-11e7-8fd0-6ee4dd489724.png)

Thanks,
Matt Joste
QA and Agile Specialist
Ryerson University

**Comment by pekkaklarck** [comment]
Awesome! We are going to do some bigger changes to the site in the near future. It might be that we wait until that before adding new content, so it may take a little time before this get added.

**Comment by Mattje1** [comment]
Ok. Thanks Pekka.

We appreciate your efforts in this endeavour

**Comment by Tattoo** [comment]
Thanks on my part as well!
