### ISSUE TITLE
Update Robot Framework users list

### ISSUE THREAD

**Issue by everthuijben** [robotframework/robotframework.github.com#48]
Hi,

As already mentioned, I like to add my company to the Robot users list on your website.

Here is my description:

Axon is using Robot Framework in testing embedded software and hardware development of broadcast equipment. We automate testing as much as possible in order to speed up development while guarantee quality. The Robot Framework is the perfect tool for this job.

You can find our website at http://www.axon.tv

Thankx in advance,

Evert Huijben
Axon Digital Design
Gilze, The Nederlands
![axon_logo_rgb_1024px](https://user-images.githubusercontent.com/4189327/32381044-05b74d9e-c0b2-11e7-9829-1fdec99b8c95.png)

**Comment by Tattoo** [comment]
Thanks for contributing! 

You were added in 10f27aa1e011ca7e51fe91589ffd06b82a7dc6ff
