### ISSUE TITLE
Adding opendaylight to users list 

### ISSUE THREAD

**Issue by parlakisik** [robotframework/robotframework.github.com#49]
Opendaylight have been using robotframework for sdn based controller test . 

This information and picture will be pushed to page .

<div class="link">
            <a href="https://www.opendaylight.org" target="_blank">
              <img src="/img/users/opendaylight.png" />
            </a>
            <p>
              OpenSource sdn platform Opendaylight is using Robot Framework for unit test 
              and integration tests between different services .
               if you are interested how sdn network can be test with robotframework .
               You can check  <a href="https://wiki.opendaylight.org/view/CrossProject:Integration_Group:Create_System_Test_Environment#Install_Robot_Framework">
                wiki </a> page.

            </p>
          </div>

![opendaylight](https://user-images.githubusercontent.com/4056995/32622552-0df4eaae-c538-11e7-9fd6-33dddbbc7089.png)

**Comment by pekkaklarck** [comment]
Cool, thanks! I doubt everyone knows what SDN means, so perhaps better to use "software-defined networking (SDN)" instead.

**Comment by parlakisik** [comment]
sure i will update

**Comment by Tattoo** [comment]
Added in 35e649c4942bd68054bc3c6ccf427223a160be8f

I edited the description slightly. If you want to fine-tune it still, please re-open this issue. 

Thanks for contributing!

**Comment by parlakisik** [comment]
thanks , i couldn't push my changes .
