### ISSUE TITLE
List TestFX Library in RobotFramework.org

### ISSUE THREAD

**Issue by codecube** [robotframework/robotframework.github.com#56]
Hi, 
We just developed and open sourced a Robot Framework TestFX Library to support RF test automation of JavaFX applications. The library is based on TestFX framework and Robot Framework JavaLib. It has almost 200 keywords, all documented and with tests.

When we decided to open source it, I shared in the Robot Framework slack, and I was advised to create a issue here, in order to list the library in robotframework.org. 

You can find the TestFX Library in: https://github.com/Altran-PT-GDC/Robot-Framework-Test-FX-Library

Thank you.
Best Regards,

Pedro

**Comment by pekkaklarck** [comment]
Awesome! We are just about to release a new version of robotframework.org and it may be best that we wait until it's released before we add this new library there.

**Comment by Tattoo** [comment]
@codecube thanks for contributing!
