### ISSUE TITLE
Add Adwisit as user

### ISSUE THREAD

**Issue by sabotchick** [robotframework/robotframework.github.com#58]
Adwisit would be happy to be listed as a user. 
Text:
> Adwisit uses Robot Framework to automate end-to-end testing of business processes for customers with a complex structure of third-party products, handling both web and desktop applications.

Website: 
www.adwisit.se

Logo:
![logo adwisit ingen bakgrund vit kontur beskuren](https://user-images.githubusercontent.com/26596054/36525265-7818c64e-17a9-11e8-8f8d-01d634affcb9.png)

Thanks!
/Kristina Sabotic

**Comment by pekkaklarck** [comment]
Awesome! We are just about to release a new version of robotframework.org and will add Adwisit once the new version is up.

**Comment by Tattoo** [comment]
@sabotchick thanks for contributing

**Comment by sabotchick** [comment]
Oups, the link points to http://robotframework.org/www.adwisit.se, when it should be only www.adwisit.se

**Comment by Tattoo** [comment]
@sabotchick Good catch! It should be fixed now

-TKa
