### ISSUE TITLE
RobotCorder

### ISSUE THREAD

**Issue by aks1589** [robotframework/robotframework.github.com#59]
**Name of the tool**
Robot Corder

**Description**
A Robot that records user action and scans the page to generate RobotFramework test scripts (beta)
Robotcorder generates RobotFramework test script by recording user interactions and scanning the html page. 
It aims to be equivalent of Selenium IDE for RobotFramework browser test automation.

**Link to the resource**
https://github.com/sohwendy/Robotcorder

**Resource Owner**
 Wendy Soh

Additional information
http://bit.ly/robotcorder-blog

When adding a new user, also include company/organization logo.

**Comment by Tattoo** [comment]
Thanks for contributing!

I listed you under Tools > Other. If you feel some other category would fit better for Robot Corder, please reopen this issue.
