### ISSUE TITLE
"Dos And Don'ts" explanation is broken

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework.github.com#76]
"Documentation > Getting Started > Dos And Don'ts" has explanation

> Presentation loosely based on the above how-to.

but this is wrong. It's based on "How to write good test cases", which on old page was above but now is on side. Perhaps it could be something like this:

> Slide set loosely based on "How to write good test cases" guidelines.

**Comment by stedtsa** [comment]
Changed as Slide set loosely based on 'How to write good test cases' guidelines.
