### ISSUE TITLE
Videos missing, only some videos have titles and they seem wrong

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework.github.com#77]
- Currently there are only six videos but we should have many more, including RoboCon videos. 

- Some of the videos have titles like "Create Your First Script - Part 1" below them but not all. Also, these titles seem to be linked only to http://www.robotframeworktutorial.com/, not to those videos. I think we should either add titles to all and link them to the video itself or remove the extra titles altogether.

**Comment by samipe** [comment]
a4223a599c5d93e6c9a896cbdc8e3af8c72c93a0
