### ISSUE TITLE
Add Lucid as User

### ISSUE THREAD

**Issue by rsmparthiban** [robotframework/robotframework.github.com#80]
Lucid Software from India would like to be in the user in robot framework site, please add lucid as a user.

Text:

Lucid Software is using Robot Framework for complete system automation testing of its NDT software products. Necessary unique libraries are created to test the applications in both Windows and WPF formats.

Website:

http://www.kovidndt.com

Logo:

    
![lucid](https://user-images.githubusercontent.com/16665692/39242589-1eae9de2-48a8-11e8-8a08-59150d275035.png)

**Comment by stedtsa** [comment]
Lucid Software added as user.
