### ISSUE TITLE
List TestFXLibrary with remote interface support 

### ISSUE THREAD

**Issue by codecube** [robotframework/robotframework.github.com#81]
Hi all, our last release of TestFXLibrary (1.0.1) includes a remote interface. Can you please mention in the RF.org website in the Libraries page this fact? 
https://github.com/Altran-PT-GDC/Robot-Framework-Test-FX-Library/releases
https://github.com/Altran-PT-GDC/Robot-Framework-Test-FX-Library/wiki/4.-Executing-Test-Scripts#running-remote-library
"Has also remote interface support".

Thank you.

Best regards, 
Pedro Costa

**Comment by stedtsa** [comment]
Done:

TestFX Library
Library to enable to test Java FX applications using the TestFX framework. Has also remote interface support.
