### ISSUE TITLE
Alfastrahovanie uses Robot Framework

### ISSUE THREAD

**Issue by korolmi** [robotframework/robotframework.github.com#82]
We are using RF as a main regression testing tool for our SAP FS CM system. We are in the beginning of our ATDD path, RF is our main vehicle here as well.

WWW: https://www.alfastrah.ru/

Logo: https://www.alfastrah.ru/local/templates/adaptive/html/new_index/dist/img/logo/logo-red.png

(Alfastrahovanie is #2 insurance company in Russia)

**Comment by stedtsa** [comment]
Done
