### ISSUE TITLE
Keyword to send continuous traffic[ethernet packets]

### ISSUE THREAD

**Issue by sshajiya** [robotframework/robotframework.github.com#83]
Hi Team,
I have a requirement to send continuous vlan tagged traffic from Linux PC to my network Device(Switch).
I have used send, Sr1,srloop to send bursty/counted number of packets using 'count' in scapy library.
I haven't find any option to send continuous packets providing timeout option.
Kindly let me know the feasibility of built in API's to implement this task.
Thanks for your support.

**Comment by pekkaklarck** [comment]
This issue tracker is for requests to add/modify information at http://robotframework.org. You can find actual support forums via those pages.
