### ISSUE TITLE
Not able to execute ride.py

### ISSUE THREAD

**Issue by baptubit** [robotframework/robotframework.github.com#86]
Hi All,
I have installed Python with Robot framework as per the following steps:
1.First Install Python library[latest 2.7>]
2.set the path in the following format:
    -->right click on "My computer"-->property-->Advanced system settings-->Environmental Variables-->System variables-->select path variable and edit-->add the path string with "C:\Python27;C:\Python27\Scripts"[varies system to system]--->save and come out
3.download "wxpython 2.8.12.1"
4.download "setuptools-39.2.0.zip"
5.extract the zipped file & go to the folder
6.in the above folder path in windows replace with cmd & enter
   [example--"C:\Users\xxxxxxxxx\Downloads\setuptools-39.2.0" with cmd & enter]
7.command prompt will open
8.here execute the command "python setup.py install"
9.download "pip-10.0.1.tar.gz"
5.extract the zipped file & go to the folder
6.in the above folder path in windows replace with cmd & enter
   [example--"C:\Users\xxxxxxxxx\Downloads\pip-10.0.1" with cmd & enter]
7.command prompt will open
8.here execute the command "python setup.py install"
9.now from "run ",execute the cmd command & execute the following command:
  a)pip install robotframework
  b)pip install robotframework-ride
  c)pip install robotframework-selenium2library
  d)pip install selenium
  e)pip install decorator
   f)pip install docutils
   g)pip install xlrd
   h)pip install xlwt
   i)pip install xlutils
====================================
after all the installation completed I tried to execute ride.py but its giving following error:
Wrong wxPython version.
You need to install wxPython 2.8.12.1 with unicode support to run RIDE.
wxPython 2.8.12.1 can be downloaded from http://sourceforge.net/projects/wxpytho
n/files/wxPython/2.8.12.1/
=============================
I have verified the following steps also ,but its giving error:
**Step1**
>>> import wx

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import wx
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\__init__.py", line 45, in <module>
    from wx._core import *
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 4, in <module>
    import _core_
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Step2**
rebooted my system after installation
**Step3**
C:\Python27>python.exe -c "from robotide import main;main()"
Wrong wxPython version.
You need to install wxPython 2.8.12.1 with unicode support to run RIDE.
wxPython 2.8.12.1 can be downloaded from http://sourceforge.net/projects/wxpytho
n/files/wxPython/2.8.12.1/

**Comment by pekkaklarck** [comment]
Please ask questions on support forums, not in issue tracker. Also, this would be totally invalid tracker for this kind of questions. Finally, the description is so badly formatted it's nearly unreadable.
