### ISSUE TITLE
Add OpenDrives for RF Users

### ISSUE THREAD

**Issue by Tattoo** [robotframework/robotframework.github.com#87]
On behalf of John Hautzinger

Description:

OpenDrives is using Robot Framework to accelerate the development of our proprietary software platform and state of the art hardware NAS appliances.  As Open Drives strives to lead the industry in speed and ease of use we needed a tool that could match that.  Robot Framework was an easy choice.

Logo: 
![opendrives - rgb-01](https://user-images.githubusercontent.com/280218/41774915-5613d3b0-762a-11e8-8bcc-112a43a5e4fe.png)

**Comment by BrewerJack** [comment]
Thank you for this.

**Comment by stedtsa** [comment]
In progress. Changes committed to 'feature_user_to_users' branch.
