### ISSUE TITLE
Integration with Winium

### ISSUE THREAD

**Issue by viva7867** [robotframework/robotframework.github.com#90]
Hi 

Any Plan for Robot framework integration with winium( opensource) to have one library to support following.

Windows Desktop (WPF, WinForms) Apps
Windows Store or Universal Apps for Windows Phone
Windows Phone Silverlight Apps
Winium Reference Link 👍
https://github.com/2gis/Winium

Thanks
Viva

**Comment by eduardoalda** [comment]
Any updates?
