### ISSUE TITLE
Add Rocla (http://rocla.com/) to 'http://robotframework.org/#users' page 

### ISSUE THREAD

**Issue by stedtsa** [robotframework/robotframework.github.com#96]
Description:
Rocla is using Robot Framework widely in development and testing of the software for trucks and Automated guided vehicles (AGV’s).
![rocla-cmyk 1](https://user-images.githubusercontent.com/16814442/45210534-8f139b00-b298-11e8-8294-4824505aa157.png)

Rocla's url is http://rocla.com/

**Comment by gnurenga** [comment]
@stedtsa you also share the website url for ROCLA. It will be useful when linking the logo and website.

**Comment by stedtsa** [comment]
http://rocla.com

ma 10. syyskuuta 2018 klo 11.12 Rengaraj <notifications@github.com>
kirjoitti:

**Comment by stedtsa** [comment]
> @stedtsa you also share the website url for ROCLA. It will be useful when linking the logo and website.

Added.

**Comment by stedtsa** [comment]
Rocla added to http://robotframework.org/#users
