### ISSUE TITLE
List Mainframe 3270 Library

### ISSUE THREAD

**Issue by jdagomes** [robotframework/robotframework.github.com#97]
Hi all,

We just released a Robot Framework Library that allows to create automated test scripts to test IBM Mainframe 3270. Can you please add it to the External Libraries in robotframework.org?

https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library

Thank you.

Best regards,
João Gomes

**Comment by stedtsa** [comment]
mainframe 3270 library added.
