### ISSUE TITLE
New libraries

### ISSUE THREAD

**Issue by VVilde** [robotframework/robotframework.github.com#98]
Found some new resources to add to the Extrnal Libraries:

Debug Library
https://github.com/xyb/robotframework-debuglibrary
A debug library for RobotFramework, which can be used as an interactive shell(REPL) also.

Selenium2Screenshots
https://pypi.org/project/robotframework-selenium2screenshots
Library for capturing annotated screenshots with Selenium2Library.

RESTinstance
https://github.com/asyrjasalo/RESTinstance
Robot Framework test library for (RESTful) JSON APIs

**Comment by stedtsa** [comment]
debug library added to external libraries, restinstance already existed

**Comment by stedtsa** [comment]
libraries added
